apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: acme
spec:
  virtualhost:
    fqdn: web02.lab
  routes:
    - conditions:
      - prefix: /
      services:
        - name: frontend
          port: 3000
